package go_converter

import (
	"text/template"
)

var GoConverterTmpl = template.Must(template.New("GoConverterTmpl").Parse(`
// Code generated by go-codegen error protobuf go_converter; DO NOT EDIT

package {{ .PackageName }}

{{ .ImportPackages }}

func ConvertErrorToProto(derr {{ .ErrorPackagePrefix }}Error) *{{ .ProtoPackagePrefix }}Error {
	details := make([]*{{ .ProtoPackagePrefix }}ErrorDetail, len(derr.Details()))
	for i := range derr.Details() {
		details[i] = &{{ .ProtoPackagePrefix }}ErrorDetail{
			Code: derr.Details()[i].Code().String(),
			Args: derr.Details()[i].Args(),
		}
	}
	return &{{ .ProtoPackagePrefix }}Error{
		Code:    derr.Code().String(),
		Details: details,
	}
}
`))
