package go_constructor_test

import (
	cmd "github.com/hori-ryota/go-codegen/codegen"
	"github.com/mattn/go-shellwords"
	"github.com/spf13/cobra"
)

func Example() {
	input := "go_constructor -t internal/testdata"

	cmd := prepareCmdWithStdout(input)
	err := cmd.Execute()
	if err != nil {
		panic(err)
	}
	// Output:
	// // Code generated by go-codegen go_constructor; DO NOT EDIT.
	//
	// package example
	//
	// import (
	// 	time "time"
	// )
	//
	// func NewPerson(
	// 	id string,
	// 	name string,
	// ) Person {
	// 	return Person{
	// 		id:        id,
	// 		name:      name,
	// 		createdAt: time.Now(),
	// 	}
	// }
	//
	// func NewPersonService(
	// 	id string,
	// ) *PersonService {
	// 	return &PersonService{
	// 		id: id,
	// 	}
	// }
	//
	// func NewArmedWarrior(
	// 	person Person,
	// 	armament string,
	// ) ArmedWarrior {
	// 	return ArmedWarrior{
	// 		Person:   person,
	// 		armament: armament,
	// 	}
	// }
}

func prepareCmdWithStdout(input string) *cobra.Command {
	input += " --useStdOut"
	args, err := shellwords.Parse(input)
	if err != nil {
		panic(err)
	}
	cmd := cmd.NewRootCmd()
	cmd.SetArgs(args)
	return cmd
}
