// Code generated by go-codegen go_constructor; DO NOT EDIT.

package typeutil

import (
	"go/types"
)

func NewPrinter(
	dstPackage *types.Package,
) Printer {
	return Printer{
		dstPackage: dstPackage,
	}
}
