// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/error.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "google.golang.org/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 string         `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Details              []*ErrorDetail `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_faef5ce421884d5a, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetDetails() []*ErrorDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

type ErrorDetail struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorDetail) Reset()         { *m = ErrorDetail{} }
func (m *ErrorDetail) String() string { return proto.CompactTextString(m) }
func (*ErrorDetail) ProtoMessage()    {}
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_faef5ce421884d5a, []int{1}
}

func (m *ErrorDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDetail.Unmarshal(m, b)
}
func (m *ErrorDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDetail.Marshal(b, m, deterministic)
}
func (m *ErrorDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDetail.Merge(m, src)
}
func (m *ErrorDetail) XXX_Size() int {
	return xxx_messageInfo_ErrorDetail.Size(m)
}
func (m *ErrorDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDetail proto.InternalMessageInfo

func (m *ErrorDetail) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ErrorDetail) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "testdata.Error")
	proto.RegisterType((*ErrorDetail)(nil), "testdata.ErrorDetail")
}

func init() { proto.RegisterFile("proto/error.proto", fileDescriptor_faef5ce421884d5a) }

var fileDescriptor_faef5ce421884d5a = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0x65, 0x28, 0x7f, 0x7a, 0x9d, 0xb0, 0x84, 0xd4, 0xb1, 0xea, 0xd4, 0x25, 0x3e, 0x09,
	0xc4, 0x0b, 0x54, 0xc0, 0xc4, 0x50, 0x65, 0x64, 0x73, 0x13, 0xcb, 0xb1, 0x94, 0xe4, 0xd0, 0xe5,
	0x18, 0x78, 0x00, 0xde, 0x1b, 0xf9, 0x12, 0x4b, 0x0c, 0x9d, 0xee, 0x27, 0x9f, 0xbf, 0xef, 0xec,
	0x83, 0x87, 0x2f, 0x26, 0x21, 0x0c, 0xcc, 0xc4, 0x4e, 0xb3, 0xbd, 0x97, 0x30, 0x49, 0xeb, 0xc5,
	0xef, 0x3f, 0xe0, 0xe6, 0x2d, 0x37, 0xac, 0x85, 0x55, 0x43, 0x6d, 0xd8, 0x9a, 0x9d, 0x39, 0xac,
	0x6b, 0xcd, 0x16, 0xe1, 0xae, 0x0d, 0xe2, 0x53, 0x3f, 0x6d, 0xaf, 0x76, 0xd7, 0x87, 0xcd, 0xd3,
	0xa3, 0x2b, 0xa0, 0x53, 0xea, 0x55, 0xbb, 0x75, 0xb9, 0xb5, 0x7f, 0x81, 0xcd, 0xbf, 0xf3, 0x8b,
	0x4e, 0x0b, 0x2b, 0xcf, 0x71, 0x16, 0xae, 0x6b, 0xcd, 0xc7, 0x5f, 0x03, 0x55, 0x43, 0x83, 0x8b,
	0x49, 0xba, 0xef, 0xb3, 0xeb, 0x88, 0x13, 0xff, 0x90, 0x78, 0x17, 0x29, 0x33, 0x31, 0x8c, 0x6e,
	0x7e, 0x7d, 0x99, 0x7e, 0x04, 0x1d, 0x73, 0xca, 0x9f, 0x39, 0x99, 0xcf, 0xf7, 0x05, 0x6c, 0x68,
	0xc0, 0x0c, 0x57, 0x4a, 0x63, 0xa4, 0x6a, 0xc1, 0xb1, 0x54, 0xd5, 0x60, 0x1a, 0x25, 0xf0, 0xe8,
	0x7b, 0x2c, 0x3e, 0xd4, 0xb5, 0x9c, 0x6f, 0xb5, 0x3c, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xdf,
	0x04, 0x32, 0x92, 0x32, 0x01, 0x00, 0x00,
}
