// Code generated by go-codegen go_constructor; DO NOT EDIT.

package application

import (
	domain "github.com/hori-ryota/go-codegen/codegen/api/internal/testdata/internal/domain"
)

func NewSomeActorDescription(
	id string,
	typ string,
) SomeActorDescription {
	return SomeActorDescription{
		id:  id,
		typ: typ,
	}
}

func NewDoingSomethingWithOutputAndActorUsecase() DoingSomethingWithOutputAndActorUsecase {
	return DoingSomethingWithOutputAndActorUsecase{}
}

func NewDoingSomethingWithOutputAndActorUsecaseInput(
	stringParam string,
	intParam int,
	int64Param int64,
	uintParam uint,
	uint64Param uint64,
	float32Param float32,
	float64Param float64,
	bytesParam []byte,
	anonymousNestedStructParam struct{ StringParam string },
	namedNestedStructParam NamedSomeType,
	stringEnumParam domain.StringEnum,
	intEnumParam domain.IntEnum,
	stringSliceParam []string,
	intSliceParam []int,
	int64SliceParam []int64,
	uintSliceParam []uint,
	uint64SliceParam []uint64,
	float32SliceParam []float32,
	float64SliceParam []float64,
	bytesSliceParam [][]byte,
	anonymousNestedStructSliceParam []struct{ StringParam string },
	namedNestedStructSliceParam []NamedSomeType,
	stringEnumSliceParam []domain.StringEnum,
	intEnumSliceParam []domain.IntEnum,
) DoingSomethingWithOutputAndActorUsecaseInput {
	return DoingSomethingWithOutputAndActorUsecaseInput{
		stringParam:                     stringParam,
		intParam:                        intParam,
		int64Param:                      int64Param,
		uintParam:                       uintParam,
		uint64Param:                     uint64Param,
		float32Param:                    float32Param,
		float64Param:                    float64Param,
		bytesParam:                      bytesParam,
		anonymousNestedStructParam:      anonymousNestedStructParam,
		namedNestedStructParam:          namedNestedStructParam,
		stringEnumParam:                 stringEnumParam,
		intEnumParam:                    intEnumParam,
		stringSliceParam:                stringSliceParam,
		intSliceParam:                   intSliceParam,
		int64SliceParam:                 int64SliceParam,
		uintSliceParam:                  uintSliceParam,
		uint64SliceParam:                uint64SliceParam,
		float32SliceParam:               float32SliceParam,
		float64SliceParam:               float64SliceParam,
		bytesSliceParam:                 bytesSliceParam,
		anonymousNestedStructSliceParam: anonymousNestedStructSliceParam,
		namedNestedStructSliceParam:     namedNestedStructSliceParam,
		stringEnumSliceParam:            stringEnumSliceParam,
		intEnumSliceParam:               intEnumSliceParam,
	}
}

func NewNamedSomeType(
	stringParam string,
) NamedSomeType {
	return NamedSomeType{
		stringParam: stringParam,
	}
}

func NewDoingSomethingWithOutputAndActorUsecaseOutput(
	stringParam string,
) DoingSomethingWithOutputAndActorUsecaseOutput {
	return DoingSomethingWithOutputAndActorUsecaseOutput{
		stringParam: stringParam,
	}
}

func NewDoingSomethingWithOutputWithoutActorUsecase() DoingSomethingWithOutputWithoutActorUsecase {
	return DoingSomethingWithOutputWithoutActorUsecase{}
}

func NewDoingSomethingWithOutputWithoutActorUsecaseInput(
	stringParam string,
) DoingSomethingWithOutputWithoutActorUsecaseInput {
	return DoingSomethingWithOutputWithoutActorUsecaseInput{
		stringParam: stringParam,
	}
}

func NewDoingSomethingWithOutputWithoutActorUsecaseOutput(
	stringParam string,
) DoingSomethingWithOutputWithoutActorUsecaseOutput {
	return DoingSomethingWithOutputWithoutActorUsecaseOutput{
		stringParam: stringParam,
	}
}

func NewDoingSomethingWithoutOutputAndActorUsecase() DoingSomethingWithoutOutputAndActorUsecase {
	return DoingSomethingWithoutOutputAndActorUsecase{}
}

func NewDoingSomethingWithoutOutputAndActorUsecaseInput(
	stringParam string,
) DoingSomethingWithoutOutputAndActorUsecaseInput {
	return DoingSomethingWithoutOutputAndActorUsecaseInput{
		stringParam: stringParam,
	}
}

func NewDoingSomethingWithoutOutputWithActorUsecase() DoingSomethingWithoutOutputWithActorUsecase {
	return DoingSomethingWithoutOutputWithActorUsecase{}
}

func NewDoingSomethingWithoutOutputWithActorUsecaseInput(
	stringParam string,
) DoingSomethingWithoutOutputWithActorUsecaseInput {
	return DoingSomethingWithoutOutputWithActorUsecaseInput{
		stringParam: stringParam,
	}
}
