// Code generated by go-codegen error protobuf go_converter; DO NOT EDIT

package httprpc

import (
	protobuf "github.com/hori-ryota/go-codegen/codegen/api/internal/testdata/external/adapter/protobuf"
	domain "github.com/hori-ryota/go-codegen/codegen/api/internal/testdata/internal/domain"
)

func ConvertErrorToProto(derr domain.Error) protobuf.Error {
	details := make([]*protobuf.ErrorDetail, len(derr.Details()))
	for i := range derr.Details() {
		details[i] = &protobuf.ErrorDetail{
			Code: derr.Details()[i].Code().String(),
			Args: derr.Details()[i].Args(),
		}
	}
	pe := protobuf.Error{
		Code:    derr.Code().String(),
		Details: details,
	}
	return pe
}
