// Code generated by go-codegen go_accessor; DO NOT EDIT.

package application

func (m DoingSomethingWithOutputAndActorUsecaseInput) StringParam() string {
	return m.stringParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) IntParam() int {
	return m.intParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) Int64Param() int64 {
	return m.int64Param
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) UintParam() uint {
	return m.uintParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) Uint64Param() uint64 {
	return m.uint64Param
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) Float32Param() float32 {
	return m.float32Param
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) Float64Param() float64 {
	return m.float64Param
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) AnonymousNestedStructParam() struct{ StringParam string } {
	return m.anonymousNestedStructParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) NamedNestedStructParam() NamedSomeType {
	return m.namedNestedStructParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) StringSliceParam() []string {
	return m.stringSliceParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) IntSliceParam() []int {
	return m.intSliceParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) Int64SliceParam() []int64 {
	return m.int64SliceParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) UintSliceParam() []uint {
	return m.uintSliceParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) Uint64SliceParam() []uint64 {
	return m.uint64SliceParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) Float32SliceParam() []float32 {
	return m.float32SliceParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) Float64SliceParam() []float64 {
	return m.float64SliceParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) AnonymousNestedStructSliceParam() []struct{ StringParam string } {
	return m.anonymousNestedStructSliceParam
}

func (m DoingSomethingWithOutputAndActorUsecaseInput) NamedNestedStructSliceParam() []NamedSomeType {
	return m.namedNestedStructSliceParam
}

func (m DoingSomethingWithOutputAndActorUsecaseOutput) StringParam() string {
	return m.stringParam
}

func (m DoingSomethingWithOutputWithoutActorUsecaseInput) StringParam() string {
	return m.stringParam
}

func (m DoingSomethingWithOutputWithoutActorUsecaseOutput) StringParam() string {
	return m.stringParam
}

func (m DoingSomethingWithoutOutputAndActorUsecaseInput) StringParam() string {
	return m.stringParam
}

func (m DoingSomethingWithoutOutputWithActorUsecaseInput) StringParam() string {
	return m.stringParam
}

func (m NamedSomeType) StringParam() string {
	return m.stringParam
}

func (m SomeActorDescription) ID() string {
	return m.id
}

func (m SomeActorDescription) Typ() string {
	return m.typ
}
